### ISSUE TITLE
Sharing: You need pulse audio 1.0 and above to support audio share

### ISSUE THREAD

**Issue by kendal-pioneer** [probonopd/Zoom.AppImage#8]
`pulseaudio-utils-32bit-16.1-1.2.x86_64
libpulse0-32bit-16.1-1.2.x86_64
alsa-plugins-pulse-1.2.7.1-2.2.x86_64
pulseaudio-setup-16.1-1.2.x86_64
alsa-plugins-pulse-32bit-1.2.7.1-2.2.x86_64
libpulse-mainloop-glib0-16.1-1.2.x86_64
libpulse0-16.1-1.2.x86_64
pipewire-pulseaudio-0.3.58-1.1.x86_64
`
`pipewire-spa-tools-0.3.58-1.1.x86_64
pipewire-0.3.58-1.1.x86_64
libpipewire-0_3-0-0.3.58-1.1.x86_64
pipewire-tools-0.3.58-1.1.x86_64
pipewire-alsa-0.3.58-1.1.x86_64
pipewire-spa-plugins-0_2-0.3.58-1.1.x86_64
pipewire-modules-0_3-0.3.58-1.1.x86_64
pipewire-pulseaudio-0.3.58-1.1.x86_64
`
My system is openSUSE Tumbleweed
And it uses pipewire-pulseaudio

**Comment by probonopd** [comment]
Can you try on a system without Wayland and without PipeWire?

**Comment by kendal-pioneer** [comment]
It works correctly

**Comment by probonopd** [comment]
Thanks for confirmin @kendal-pioneer. I am not interested in investing any time in Wayland but if someone cares enough to send a pull request I will consider it, as long as it doesn't break Xorg.

**Comment by probonopd** [comment]
PLEASE NOTE: In general, you should download AppImages only from the original authors of the software (here: https://zoom.us/), but since they are not yet providing one I am offering this here. **Please contact them** if you would like to see an official one.

**Comment by myownfriend** [comment]
@kendal-pioneer 
The issue you experienced isn't with Wayland, it's just with Pipewire's PulseAudio plugin. Wayland doesn't have anything to do with audio. Try it with Pipewire again and if the issue still exists then bring if up on[ Pipewire's repository](
https://gitlab.freedesktop.org/pipewire/pipewire) so they can work on it. 

Probo doesn't really know what Wayland and Pipewire are or how they relate to each other. He saw "Pipewire" and since he's only heard of Pipewire when talking about Wayland, he assumed you're using Wayland. Since he thinks Wayland breaks everything, he saying it's the issue here even though it can't be.

Now he's using this issue you opened about an **audio** problem as an example in his thread to try to push a boycott of something that's part of Linux's **graphics** stack.

**Comment by probonopd** [comment]
Well. I'd suggest to try on a system without Wayland and without Pipewire and see whether it works correctly there. ;-)

**Comment by myownfriend** [comment]
@probonopd yes because they would be using PulseAudio directly instead of Pipewire's Pulse plugin. There was never a chance it had anything to do with Wayland because Wayland has nothing to do with audio.

You could have suggested they try Zoom on Windows and it would have worked, too. That way Pulse, Linux, and AppImage would be removed from the equation, too. It wouldn't have meant that you figured out the problem though.

Looking up the issue shows that most people fixed it by installing pulseaudio-utils.

**Comment by kendal-pioneer** [comment]
Actually if I just ignore the zoom warning/notification and although I don't get the option to share audio with video check box
I know it does actually work, regardless

**Comment by myownfriend** [comment]
Oh! I didnt realize it was working regardless of the error message lol Glad it worked!
